version: "3.8"
services:

  mindspace_api:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    network_mode: bridge
    command: ["java", "-jar", "/mindspace.jar"]
    links:
      - mindspace_db
    env_file:
      - ./config/api.env
    expose:
      - 9071
    ports:
      - 9071:9071
    depends_on:
      - mindspace_db
    volumes:
      - ./src/api/src/target/mindspace.jar:/mindspace.jar

  mindspace_db:
    image: postgres:12.3
    container_name: mindspace_db
    network_mode: bridge
    env_file:
      - ./config/.env
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - ./src/db:/var/lib/postgresql/data

  # TODO: mindspace_app -> React Native FE
  # TODO: mindspace_ai  -> Python TF model
