version: "3.8"
services:

  mindspace_db:
    image: postgres:12.3
    container_name: mindspace_db
    env_file:
      - ./config/.env
    ports:
      - "5432:5432"
    volumes:
      - ./src/db:/var/lib/postgresql/data
