version: "3.8"
services:

  mindspace_db:
    image: postgres:12.3
    container_name: mindspace_db
    env_file:
      - ./config/.env
    ports:
      - "5432:5432"
    volumes:
      - ./src/db:/var/lib/postgresql/data

  mindspace_api:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    command: ["java", "-jar", "/mindspace.jar"]
    # env_file:
    #   - ./config/api.env
    ports:
      - "9071:9071"
    depends_on:
      - mindspace_db
